# cov19.R - COVID-19 deaths in Germany

load("cov19de.RData") # generated by scrape_cov19.R

bg <- c(e="#FFCCCC", w="#CCCCFF", b="#FFCCFF")[ew]
names(bg) <- state

### Fitting
library(growthcurver)

# Fitted Cum. infections / 100,000 pop.
L <- lapply(tbl[[2]], function(x) 
  SummarizeGrowth(seq_along(x), x, bg_correct="none"))
tbl[[5]] <- data.frame(sapply(L, function(x) predict(x$model)))
row.names(tbl[[5]]) <- row.names(tbl[[2]])

# Fitted Cum. deaths / 100,000 pop.
L <- lapply(tbl[[4]], function(x) 
  SummarizeGrowth(seq_along(x), x, bg_correct="none"))
tbl[[6]] <- data.frame(sapply(L, function(x) predict(x$model)))
row.names(tbl[[6]]) <- row.names(tbl[[4]])

### Plot
library(ggplot2)
library(geofacet)
library(cowplot)
theme_set(theme_cowplot())

ti <- cbind(
  date=rep(row.names(tbl[[2]]), ncol(tbl[[2]])), 
  stack(tbl[[2]])[, c(2, 1)], stack(tbl[[5]])[, 1])
colnames(ti) <- c("date", "state", "infection", "fitted")
t2 <- tbl[[2]]

ggplot(ti, aes(as.Date(date), infection)) +
  facet_geo(~ state, grid="de_states_grid1") +
  geom_rect(aes(fill=state), xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_point(shape=1) +
  geom_line(aes(as.Date(date), fitted), color="red") +
  scale_x_date(date_labels="%-m/%-d") +
  scale_fill_manual("legend", values=bg) +
  labs(
    title = sprintf(
      "COVID-19 infections in Germany (as of %s)", tail(row.names(t2), 1)),
    caption = "Data Source: Wikipedia based on Robert Koch Institute",
    x = "Date",
    y = "Infections / 100,000 pop.") +
  geom_text(
    x=-Inf, y=Inf, aes(label=sprintf("%3.0f", t2[nrow(t2), state])),
    vjust=1.2, hjust=-0.2, size=5, check_overlap=TRUE) +
  theme(legend.position="none")

ggsave("cov19i.png", width=12, height=9, dpi=72)

t2w <- as.data.frame(lapply(t2, diff, 7))
row.names(t2w) <- row.names(t2)[-(1:7)]
tiw <- cbind(
  date=rep(row.names(t2w), ncol(t2w)), stack(t2w)[, c(2, 1)])
colnames(tiw) <- c("date", "state", "infection")
ggplot(tiw, aes(as.Date(date), infection)) +
  facet_geo(~ state, grid="de_states_grid1") +
  geom_rect(aes(fill=state), xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_hline(yintercept=50, color="gray") +
  geom_point(shape=1) +
  scale_x_date(date_labels="%-m/%-d") +
  scale_fill_manual("legend", values=rep("#F0F0F0", ncol(t2w))) +
  labs(
    title = sprintf(
      "COVID-19 last 7 days new infections in Germany (as of %s)", tail(row.names(t2), 1)),
    caption = "Data Source: Wikipedia based on Robert Koch Institute",
    x = "Date",
    y = "Last 7 days new infections / 100,000 pop.") +
  geom_text(
    x=-Inf, y=Inf, aes(label=sprintf("%4.1f", t2w[nrow(t2w), state])),
    vjust=1.2, hjust=-0.2, size=5, check_overlap=TRUE) +
  theme(legend.position="none")

ggsave("cov19iw.png", width=12, height=9, dpi=72)

td <- cbind(
  date=rep(row.names(tbl[[4]]), ncol(tbl[[4]])), 
  stack(tbl[[4]])[, c(2, 1)], stack(tbl[[6]])[, 1])
colnames(td) <- c("date", "state", "death", "fitted")
t4 <- tbl[[4]]

ggplot(td, aes(as.Date(date), death)) +
  facet_geo(~ state, grid="de_states_grid1") +
  geom_rect(aes(fill=state), xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_point(shape=1) +
  geom_line(aes(as.Date(date), fitted), color="red") +
  scale_x_date(date_labels="%-m/%-d") +
  scale_fill_manual("legend", values=bg) +
  labs(
    title = sprintf(
      "COVID-19 deaths in Germany (as of %s)", tail(row.names(t4), 1)),
    caption = "Data Source: Wikipedia based on Robert Koch Institute",
    x = "Date",
    y = "Deaths / 100,000 pop.") +
  geom_text(
    x=-Inf, y=Inf, aes(label=sprintf("%4.1f", t4[nrow(t4), state])),
    vjust=1.2, hjust=-0.2, size=5, check_overlap=TRUE) +
  theme(legend.position="none")

ggsave("cov19d.png", width=12, height=9, dpi=72)

t4w <- as.data.frame(lapply(t4, diff, 7))
row.names(t4w) <- row.names(t4)[-(1:7)]
tdw <- cbind(
  date=rep(row.names(t4w), ncol(t4w)), stack(t4w)[, c(2, 1)])
colnames(tdw) <- c("date", "state", "infection")
ggplot(tdw, aes(as.Date(date), infection)) +
  facet_geo(~ state, grid="de_states_grid1") +
  geom_rect(aes(fill=state), xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_point(shape=1) +
  scale_x_date(date_labels="%-m/%-d", limits=range(as.Date(row.names(t2w)))) +
  scale_fill_manual("legend", values=rep("#F0F0F0", ncol(t2w))) +
  labs(
    title = sprintf(
      "COVID-19 last 7 days new deaths in Germany (as of %s)", tail(row.names(t2), 1)),
    caption = "Data Source: Wikipedia based on Robert Koch Institute",
    x = "Date",
    y = "Last 7 days new deaths / 100,000 pop.") +
  geom_text(
    x=-Inf, y=Inf, aes(label=sprintf("%4.2f", t4w[nrow(t4w), state])),
    vjust=1.2, hjust=-0.2, size=5, check_overlap=TRUE) +
  theme(legend.position="none")

ggsave("cov19dw.png", width=12, height=9, dpi=72)

# matplot-like graph
ggplot(stack(t2), aes(rep(as.Date(row.names(t2)), ncol(t2)), y=values, group=ind)) +
  geom_line(aes(color=ew[ind])) + 
  geom_text(
    data=stack(t2[nrow(t2),]), 
    aes(x=as.Date(tail(row.names(t2), 1)), y=values, label=ind, color=ew[ind]), 
    hjust=-0.2) +
  scale_color_manual(values=c(e="red", w="blue", b="purple")) +
  scale_x_date(date_labels="%-m/%-d") +
  labs(
    title = sprintf(
      "COVID-19 infections in Germany (as of %s)", rownames(t2)[nrow(t2)]),
    caption = "Data Source: Wikipedia based on Robert Koch Institute",
    x = "Date", y = "Infections / 100,000 pop.") +
  theme(legend.position="none")

ggplot(stack(t4), aes(rep(as.Date(row.names(t4)), ncol(t4)), y=values, group=ind)) +
  geom_line(aes(color=ew[ind])) + 
  geom_text(
    data=stack(t4[nrow(t4),]), 
    aes(x=as.Date(tail(row.names(t4), 1)), y=values, label=ind, color=ew[ind]), 
    hjust=-0.2) +
  scale_color_manual(values=c(e="red", w="blue", b="purple")) +
  scale_x_date(date_labels="%-m/%-d") +
  labs(
    title = sprintf(
      "COVID-19 deaths in Germany (as of %s)", rownames(t4)[nrow(t4)]),
    caption = "Data Source: Wikipedia based on Robert Koch Institute",
    x = "Date", y = "Deaths / 100,000 pop.") +
  theme(legend.position="none")
