# fit_growth.R - Fitting growth curve example

# Reference of generalized logistics:
#   [1] Burger, R et al.: "Comparative analysis of phenomenological growth
#   models applied to epidemic outbreaks", 
#   Mathematical Bioscience and Engineering, 16(5), 4250-4274 (2019).
#   [2] Tsoularis, A.: "Analysis of Logistic Growth Models",
#   Res. Lett. Inf. Math. Sci., 2, 23-46 (2001).

library(growthrates)
library(doParallel)

cAIC <- function(fit) {
  ms <- fit@fit$ms # mean suquared residuals
  n <- nrow(fit@obs)
  k <- length(fit@fit$par)
  # l <- -n / 2 * (log(2 * pi * ms) + 1)
  # AIC <- -2 * l + 2 * k
  # cAIC <- AIC + 2 * k * (k + 1) / (n - k - 1)
  n * (log(2 * pi * ms) + 1) + 2 * k + 2 * k * (k + 1) / (n - k - 1) 
}

fit_growthmodel_multstart <- function(FUN, p, x, y, ...) {
  if (is.data.frame(p))
    p <- as.matrix(p)
  L <- foreach (i=seq_len(nrow(p)), 
                .options.multicore=list(preschedule=FALSE), 
                .packages="growthrates") %dopar% {
    try(fit_growthmodel(
      FUN, p[i,], x, y, ...), TRUE)
  }
  attr(L, "convergence") <- sapply(L, function(x) ifelse(
    "try-error" %in% class(x) , NA_real_, x@fit$convergence))
  attr(L, "mse") <- sapply(L, function(x) ifelse(
    "try-error" %in% class(x) , NA_real_, x@fit$ms))
  attr(L, "kappa") <- sapply(L, function(x) ifelse(
    "try-error" %in% class(x) , NA_real_, kappa(x@fit$hessian)))
  L
}

seq.log <- function(from, to, length.out=2) {
  exp(seq(log(from), log(to), length.out=length.out))
}

rate <- function(y, x=NULL) {
  if (is.null(x))
    x <- seq_along(y)
  r <- diff(y, 2) / diff(x, 2) / y[-c(1, length(y))]
  r <- r[!is.na(r) & is.finite(r)]
  r <- r[0 < r]
  stopifnot(0 < length(r))
  r
}

fit_logistic <- function(y) {
  x <- seq_along(y)
  r <- rate(y)

  lower <- c(y0=1e-5 / 2, mumax=min(r), K=max(y) / 2)
  upper <- c(y0=1e5 / 2, mumax=max(r), K=1e5)
  p <- expand.grid(
    y0=1e-5, mumax=seq.log(min(r) + 1e-6, max(r) - 1e-6, 11), K=max(y))
  
  L <- fit_growthmodel_multstart(
    grow_logistic, p, x, y, lower=lower, upper=upper,
    method="Port", control=list(iter.max=300))
  if (all(is.na(attr(L, "mse")))) return(NULL)
  L[[which.min(attr(L, "mse"))]]
}

fit_genlogistic_alpha <- function(y) {
  x <- seq_along(y)
  r <- rate(y)

  lower <- c(y0=1e-5 / 2, mumax=min(r), K=max(y) / 2, alpha=0)
  upper <- c(y0=1e5 / 2,  mumax=max(r), K=1e5,        alpha=1)
  p <- expand.grid(
    y0=1e-5, mumax=seq.log(min(r) + 1e-6, max(r) - 1e-6, 11), K=max(y), 
    alpha=1, beta=1, gamma=1)

  L <- fit_growthmodel_multstart(
    grow_genlogistic, p, x, y, which=c("y0", "mumax", "K", "alpha"),
    lower=lower, upper=upper,
    method="Port", control=list(iter.max=300))
  if (all(is.na(attr(L, "mse")))) return(NULL)
  L[[which.min(attr(L, "mse"))]]
}

fit_genlogistic_beta <- function(y) {
  x <- seq_along(y)
  r <- rate(y)

  lower <- c(y0=1e-5 / 2, mumax=min(r), K=max(y) / 2, beta=0)
  upper <- c(y0=1e5  / 2, mumax=max(r), K=1e5,        beta=Inf)
  p <- expand.grid(
    y0=1e-5, mumax=seq.log(min(r) + 1e-6, max(r) - 1e-6, 11), K=max(y), 
    alpha=1, beta=1, gamma=1)

  L <- fit_growthmodel_multstart(
    grow_genlogistic, p, x, y, which=c("y0", "mumax", "K", "beta"), 
    lower=lower, upper=upper,
    method="Port", control=list(iter.max=300))
  if (all(is.na(attr(L, "mse")))) return(NULL)
  L[[which.min(attr(L, "mse"))]]
}

fit_gompertz2 <- function(y) {
  x <- seq_along(y)
  r <- rate(y)

  lower <- c(y0=1e-5 / 2, mumax=min(r), K=max(y) / 2)
  upper <- c(y0=1e5 / 2, mumax=max(r), K=1e5)
  p <- expand.grid(
    y0=1e-5, mumax=seq.log(min(r) + 1e-6, max(r) - 1e-6, 11), K=max(y))
  
  L <- fit_growthmodel_multstart(
    grow_gompertz2, p, x, y, lower=lower, upper=upper,
    method="Port", control=list(iter.max=300))
  if (all(is.na(attr(L, "mse")))) return(NULL)
  L[[which.min(attr(L, "mse"))]]
}

fit_gompertz3 <- function(y) {
  x <- seq_along(y)
  r <- rate(y)

  lower <- c(y0=1e-5 / 2, mumax=min(r), K=max(y) / 2, lambda=-length(x))
  upper <- c(y0=1e5 / 2, mumax=max(r),  K=1e5,        lambda=length(x))
  p <- expand.grid(
    y0=1e-5, mumax=seq.log(min(r) + 1e-6, max(r) - 1e-6, 11), K=max(y), lambda=0)
  
  L <- fit_growthmodel_multstart(
    grow_gompertz3, p, x, y, lower=lower, upper=upper,
    method="Port", control=list(iter.max=300))
  if (all(is.na(attr(L, "mse")))) return(NULL)
  L[[which.min(attr(L, "mse"))]]
}

registerDoParallel(detectCores()) # hyperthreading disabled

load("cov19de.RData") # generated by scrape_cov19.R
t4 <- tbl[[4]]

funs <- c(
  "fit_logistic", "fit_genlogistic_alpha", "fit_genlogistic_beta",
  "fit_gompertz2", "fit_gompertz3")
names(funs) <- c(
  "logistic", "logistic alpha", "Richards", "Gompertz", "Gompertz lag")
Ls <- lapply(funs, function(fun) lapply(t4, fun))
cAICs <- t(sapply(Ls, function(L) sapply(L, cAIC)))
Ks <- t(sapply(Ls, function(L) sapply(L, function(x) x@par)["K", ]))

barplot(cAICs, beside=TRUE, xlab="Federal state", ylab="cAIC", main="Model comparison")
legend("topright", names(funs), fill=gray.colors(length(funs)), ncol=2, cex=0.8)

barplot(Ks, beside=TRUE, xlab="Federal state", ylab="K", main="Carrying capacity")
legend("topright", names(funs), fill=gray.colors(length(funs)), ncol=2, cex=0.8)

plot(
  cAICs[3,], cAICs[5,], type="n", 
  main="cAIC", xlab="Richards", ylab="Gompertz lag")
text(cAICs[3,], cAICs[5,], state, col=c(e="red", w="blue", b="purple")[ew])
abline(a=0, b=1, col="gray")

plot(
  Ks[3,], Ks[5,], type="n", log="xy",
  main="K", xlab="Richards", ylab="Gompertz lag")
text(Ks[3,], Ks[5,], state, col=c(e="red", w="blue", b="purple")[ew])
abline(a=0, b=1, col="gray")

K <- as.numeric(tail(t4, 1))
plot(
  K, Ks[3,], type="n", log="xy",
  main="K", xlab=sprintf("K (as of %s)", tail(row.names(t4), 1)), ylab="Richards", 
  xlim=c(1, 20), ylim=c(1, 20))
text(K, Ks[3,], state, col=c(e="red", w="blue", b="purple")[ew])
abline(a=0, b=1, col="gray")
